### ISSUE TITLE
Wrong TypeOfData data

### ISSUE THREAD

**Issue by Auberginn** [predictionmachines/SDSlite#11]
Hello,  I am trying to cast the data of a NetCDF file, where  the metadata of the variable indicates that the typeof is Int16 but the data is actually a float32. When I try to extract the data using this command I get wrong values

> Int16[,,] dataVal = ds.GetData<Int16[,,]>(variable.Name);

When I replace the Int16 by float, double, decimal or even Int32, the command throws up an exception 

> Requested variable does not exist in the data set

The DataSet Viewer see's the same thing. In the attach file, is what I get and what I should be getting.

![NetCDF GitHub sds](https://user-images.githubusercontent.com/22666269/73981578-79c4f500-4900-11ea-9a48-195a0f3af1c5.png)

**Comment by vassilyl** [comment]
Hi Auberginn, as far as I understand, the bits of each float32 were written to the file as two 16-bit words. You will need to read the variable as Int16, an then to manually convert each pair of ints to a float, i'm afraid.  [Class BitConverter](https://docs.microsoft.com/en-us/dotnet/api/system.bitconverter) may help you with this.

**Comment by Auberginn** [comment]
Hi vassilyl, I'm not sure I understand the pairing Int16 that you mention. The table data in the image corresponds to a partial printscreen cut of the grid cells values shown by the DataSet Viewer Table. When I use the GetData in C#, it returns the same values, which -19725 corresponds to the first cell of the grid located at index [0,0,0] of the Int16 array (where the structure is [latitude, longitude, value]). The value should be in Kelvin and around 245°C.

**Comment by vassilyl** [comment]
I may have misunderstood you.

>  ... but the data is actually a float32

-- what does it actually mean? Can you show actual metadata on the variable  (`sds meta <ncfile> <var>`)?

**Comment by Auberginn** [comment]
My mistake, just float. 
DataFlow Shell version 1.3.14517.0
DataSet Core version 1.3.14517.0

>$dataset = Y2010M01.nc
Attached new DataSet at $dataset with id=1
>show $dataset meta t2m
$dataset net.pipe://localhost/microsoft/research/science/data/StorageService/bebd021e-5c80-40cd-8f7f-d6c654d83492/
msds:nc?file=E:\era5land\Y2010M01.nc
  [-6] t2m of type Int16 (time:744) (latitude:231) (longitude:441)
                Name = t2m
          _FillValue = -32767
               units = K
           long_name = 2 metre temperature
          add_offset = 260.533688291066
        scale_factor = 0.000845463766003984
       missing_value = -32767
>

**Comment by SravaniBeeram** [comment]
> My mistake, just float.
> DataFlow Shell version 1.3.14517.0
> DataSet Core version 1.3.14517.0
> 
> > $dataset = Y2010M01.nc
> > Attached new DataSet at $dataset with id=1
> > show $dataset meta t2m
> > $dataset net.pipe://localhost/microsoft/research/science/data/StorageService/bebd021e-5c80-40cd-8f7f-d6c654d83492/
> > msds:nc?file=E:\era5land\Y2010M01.nc
> > [-6] t2m of type Int16 (time:744) (latitude:231) (longitude:441)
> > Name = t2m
> > _FillValue = -32767
> > units = K
> > long_name = 2 metre temperature
> > add_offset = 260.533688291066
> > scale_factor = 0.000845463766003984
> > missing_value = -32767
> 
> ![NetCDF GitHub sds 2](https://user-images.githubusercontent.com/22666269/74054983-19d85800-49ad-11ea-980d-a0c208c9cdbe.png)

I am having the same issue..can you please let me know if you were able to resolve this?

**Comment by vassilyl** [comment]
SDSLite is transparent in regards to attribute conventions except for "missing_value".
In this particular case the library returns int16 values stored in the file, e.g. `-19725`. The `scale_factor` and `add_offset` metadata on the variable indicates how to convert the stored values to "physical" ones: `-19725 * 0.000845463766003984 + 260.533688291066 = 243.8569155066374`.
See Appendix A: Attribute Conventions at https://www.unidata.ucar.edu/software/netcdf/docs/attribute_conventions.html.
