### ISSUE TITLE
Licensing: MIT or MSR-LA?

### ISSUE THREAD

**Issue by vadim-z** [predictionmachines/SDSlite#12]
Hello,

The project is licensed under MIT license according to the file https://github.com/predictionmachines/SDSlite/blob/master/Licence.txt. 

However,  files  in the ScientificDataSet directory, for example, 
https://github.com/predictionmachines/SDSlite/blob/master/ScientificDataSet/Providers/NetCDF/NetCdfVariable.cs, contain the headings which state "This code released under the terms of the Microsoft Research License Agreement (MSR-LA)". This is quite a different and rather restrictive license.

Would you please clarify the licensing conditions? It's better to fix headings if it is possible, i.e. if copyright holder permits it.

With best regards.

**Comment by vassilyl** [comment]
Thanks for flagging this. A the code in this repository is under MIT. I've removed references to outdated MSR-LA in [d5c4051](https://github.com/predictionmachines/SDSlite/commit/d5c40512381ca6bdb65320dd743090fda07d53d6).
