### ISSUE TITLE
Bad Chunksize exception when creating a NETCDF file

### ISSUE THREAD

**Issue by hferg** [predictionmachines/SDSlite#2]
Hello
I am trying to run a global ecology model (Madingley model) under a Unix environment, and so using SDSLite. I am getting a bad chunksize exception when the model gets to creating an output netcdf file to store the simulation output when the model runs over a grid of the earth's surface (exception detail attached). This error does not occur when running the model over a single location, so I assume it is to do with the specifics of a gridded output file. Do you have any ideas what is causing this and how I might resolve it?

[exception.txt](https://github.com/predictionmachines/SDSlite/files/698637/exception.txt)

**Comment by vassilyl** [comment]
Not enough information to reproduce the issue. Most likely, this is NetCDF error to be discussed at [unidata](https://www.unidata.ucar.edu/software/netcdf/).
