### ISSUE TITLE
Need some help implementing netcdf reader in VS

### ISSUE THREAD

**Issue by benberlin7** [predictionmachines/SDSlite#22]
Hey there,

I'm using VisualStudio 2019 on a win10 machine. I'm pretty new to VS so maybe my question comes from a lack of understanding. 

I tried the code from the [tutorial ](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwii6uHr07TtAhXOGewKHZhUB-cQFjABegQIBhAC&url=https%3A%2F%2Fwww.microsoft.com%2Fen-us%2Fresearch%2Fuploads%2Fprod%2F2010%2F03%2FIntroduction-to-Scientific-DataSet-1.3.pdf&usg=AOvVaw2hZCvDu-6MMl3P9bFqLVNm)with a csv file and it worked quite good. (except the dataset.Show() method didn't exist?).

Then I wanted to load a .nc file (netcdf) into visual studio (c# console) , so I downloaded the _netCDF4.7.2-NC4-64.exe_ file from
https://www.unidata.ucar.edu/software/netcdf/docs/winbin.html

I installed everything and added the "C:\Program Files\netCDF 4.7.2\bin\" to the system path variables.
Then I tried the code :

`using System;
using System.Linq;
using Microsoft.Research.Science.Data; 
using Microsoft.Research.Science.Data.Imperative;

namespace SDS_test
{
    class Program
    {
        
        static void Main(string[] args)
        {

            // read input data
            var dataset = DataSet.Open("C:\\Users\\X\\Downloads\\sample.nc");`

But I got the following error : 
ArgumentException: This 32-bit process failed to load the library C:\Users\X\source\repos\SDS_test\SDS_test\bin\Debug\netcdf.dll. Native error message is 'Das System kann die angegebene Datei nicht finden
(system can't find file)

  | Message | "Failed to create DataSet instance from uri C:\\Users\\X\\Downloads\\sample.nc: Der Typeninitialisierer für \"NetCDFInterop.NetCDFDynamic\" hat eine Ausnahme verursacht." 

I tried to solve this by adding all the files to the project (couldn't do it as a reference because they are native dlls). :

I added the dll's, headers and .lib files via "Add existing element..." (as a link). I set the "Build Action" of each file to  "Content" and "Copy to Output Directory" to "Copy if Newer". 

So the file netcdf.dll is copied to the folder when the build starts and exists at "\Debug\netcdf.dll.".
Still I get the same errors as seen above .

I don't know how to solve this. Would very much appreciate any help.
Thanks in advance!

**Comment by MutterOberin** [comment]
Hi!

You installed the 64bit Version. Please make sure that you compile your project also as x64. Try setting it explicitly as solution platform (it is next to Debug / Release). If x64 does not exist there create it!

That should help. 

Another hint: If you have the .nc file. You can inspect it by using "ncdump -h example.nc" in the windows cmd or other shell. This helps you seeing dimensions, variables and attributes of that file. The -h stands for "header". Get a good understanding of what you have in your file and what you want from it first.

**Comment by benberlin7** [comment]
Thank you! That helped me - it is working now.
