### ISSUE TITLE
Convert to Standard Library?

### ISSUE THREAD

**Issue by Jared-Henderson** [predictionmachines/SDSlite#23]
I have been attempting to include SDSLite in a self-published dotnet core app, and I have been having linker issues with trying to include these .Net Framework libraries.  This dotnet issue is the most accurate one I've found that describes my issue:

https://github.com/mono/linker/issues/1634#issuecomment-730430380

I found a fork that attempted to migrate SDSLite to .Net Core, but it does not seem to have as much activity as SDSLite and there is no guarantee it will be maintained:

https://github.com/xfischer/SDSCore

Is there a plan to migrate this library to .Net Standard, so that it can be used in .Net 5 and beyond?

**Comment by chris1248** [comment]
Porting to .NET core should be pretty easy. 
A better fork is this one here:
https://github.com/Dzoukr/SDSCore
