### ISSUE TITLE
Under windows, error "FileNotFoundException: netcdf.dll not found in current directory" 

### ISSUE THREAD

**Issue by MathieuJack** [predictionmachines/SDSlite#26]
I try to use SDS in a .net framework console project, using the package nuget SDSLite v2.0.0.$
Program contains only this : 
`class Program
    {
        static void Main(string[] args)
        { Microsoft.Research.Science.Data.NetCDF4.NetCDFDataSet.Open(@"path_to_my_nc_file");   
 } 
  }
`

When executing this program I get this Exception:
Microsoft.Research.Science.Data.DataSetCreateException: 'Failed to create DataSet instance from uri c:\MeteoSurf\SampleFiles\32.nc: The type initializer for 'NetCDFInterop.NetCDFDynamic' threw an exception.'

Inner exception is:
FileNotFoundException: netcdf.dll not found in current directory nor on system path nor in ProgramFilesX86

What do I miss?

**Comment by vassilyl** [comment]
`SDSLite` uses original NetCDF libraries to open `.nc` files. Have you installed proper version from https://www.unidata.ucar.edu/software/netcdf/docs/winbin.html? Note that `dotnet run` starts 64-bit process by default. That means you need to install `netCDF4.7.2-NC4-64.exe`. It's totally fine to install both 32-bit and 64-bit, `SDSLite` should find proper version depending on the bitness of the process.

**Comment by MathieuJack** [comment]
Works perfectly. It was noted on Github main page, sorry.
