### ISSUE TITLE
Errors compiling in VS2017

### ISSUE THREAD

**Issue by bobasaurus** [predictionmachines/SDSlite#3]
I just cloned this project and tried compiling it in Visual Studio Community 2017 15.8.6.  I'm getting two errors:

**The command ""C:\Users\jordan\Documents\sdslitevs2017\.nuget\NuGet.exe" pack "C:\Users\jordan\Documents\sdslitevs2017\SDSLite\SDSLite.csproj" -Properties "Configuration=Debug;Platform=AnyCPU" -NonInteractive -OutputDirectory "C:\Users\jordan\Documents\sdslitevs2017\SDSLite\bin\Debug" -symbols" exited with code 1.**

**'NUnit' already has a dependency defined for 'NETStandard.Library'.**

Any suggestions?

**Comment by vassilyl** [comment]
Cannot reproduce the issue. Using fresh Windows 10.0.17134.345, [netCDF4.6.1-NC4-32](http://www.unidata.ucar.edu/downloads/netcdf/ftp/netCDF4.6.1-NC4-32.exe), freshly installed Visual Studio Community 2017 ver 15.8.9 + NUnit test adaptor. The solution successfully builds. All SDSLiteTests pass. Please be more specific about your environment when opening an issue.
