### ISSUE TITLE
Reading .nc4 dataset

### ISSUE THREAD

**Issue by benberlin7** [predictionmachines/SDSlite#32]
I have read out .nc data with c#, vs2019, netCDF 4.7.2 and SDS2.0.3 with succes, but when using the same code to open a nc4 dataset it fails with the exception : "Extension .nc4 is not registered in the factory".

`try{ dataset = DataSet.Open(path_to_nc4_file); } catch(Exception ex) { Console.Write(ex.Message); }`

Any idea how to manage that?

**Comment by MutterOberin** [comment]
I am not 100% sure, since it is some time ago and I only had a quick look into it but I have found some code where I register an extension first before I open the file.

`
protected bool Register_Extension(string extension)
        {
            Type dType = NetCDFDataSet.GetType("Microsoft.Research.Science.Data.NetCDF4.NetCDFDataSet");

            return DataSetFactory.RegisterExtension(extension, dType);
        }
`

Let me know if this helped.

**Comment by vassilyl** [comment]
You may also use a URI (string or object) to unambiguously pass parameters to `Open(...)`, e.g.
```C#
var uri = NetCDF4.NetCDFUri(){FileName="filename.nc4", OpenMode=ResourceOpenMode.ReadOnly};
var sds = DataSet.Open(uri);
```
or just
```
var sds = DataSet.Open("msds:netcdf?fileName=filename.nc4&openMode=readOnly");
```

**Comment by benberlin7** [comment]
@MutterOberin This solved the issue thanks!
@vassilyl Also thanks , it looks like a better way to conver to uri first. But I had to register nc4 first to have it workin'.
