### ISSUE TITLE
Unit Test Empty_AddVariable_string() failed

### ISSUE THREAD

**Issue by zuegerj** [predictionmachines/SDSlite#36]
Using the newest version netCDF4.9.0-NC4-64.exe, the unit test Empty_AddVariable_string() failes with follwing exception:

System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> Microsoft.Research.Science.Data.NetCDF4.NetCDFException : NetCDF error -132

**Comment by vassilyl** [comment]
The reason is here: Unidata/netcdf-c#2554
