### ISSUE TITLE
there need a .net core support

### ISSUE THREAD

**Issue by rong736** [predictionmachines/SDSlite#4]
there need a .net core support

**Comment by vassilyl** [comment]
Just checked the nuget package works with dotnet 2.1 and NetCDF 4.6.1. If you are using command line the following worked for me:
```
dotnet new console
dotnet add package sdslite
dotnet add package system.security.permissions
dotnet run
```
A sample code that opens and prints `DataSet` object successfully showed me structure of a sample NetCDF file.
