### ISSUE TITLE
SDSLite is not working on MacOSX

### ISSUE THREAD

**Issue by xfischer** [predictionmachines/SDSlite#8]
Hi and thanks for this project.

I have tested the library on Windows and it works well.
However on MacOSX (10.14.6) it is not working, as the library path is not set at all : 
https://github.com/predictionmachines/SDSlite/blob/92bf68e8a6bca37315a219190f5505d91e57dc9d/NetCDFInterop/NetCDF.cs#L569

I have tried to map to /usr/local/lib/libnetcdff.7.0.0.dylib and any other *.dylib but no success.

Can you help me with this ?

**Comment by vassilyl** [comment]
PR #31

**Comment by xfischer** [comment]
Thanks a lot @vassilyl ! Great work and very nice GitHub Actions setup, gives me inspiration :)
